using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Analyzer.Models.Enums
{
    public static class SubmachineGuns
    {
        public static List<string> ListSubmachineGuns = new List<string>()
        {
            "MAC-10",
            "MP9",
            "MP7",
            "MP5-SD",
            "UMP-45",
            "P90",
            "PP19 Bison"
        };

        public static Dictionary<string, RarityStats> ListSkinsMAC10 = new Dictionary<string, RarityStats>()
        {
            {"Hot Snakes",RarityStats.classified},
            {"Copper Borre",RarityStats.milSpec},
            {"Red Filigree",RarityStats.restricted},
            {"Case Hardened",RarityStats.restricted},
            {"Gold Brick",RarityStats.restricted},
            {"Stalker",RarityStats.covert},
            {"Fade",RarityStats.milSpec},
            {"Propaganda",RarityStats.classified},
            {"Graven",RarityStats.restricted},
            {"Commuter",RarityStats.industrialGrade},
            {"Ultraviolet",RarityStats.milSpec},
            {"Indigo",RarityStats.consumerGrade},
            {"Amber Fade",RarityStats.milSpec},
            {"Toybox",RarityStats.classified},
            {"Tatter",RarityStats.restricted},
            {"Disco Tech",RarityStats.classified},
            {"Neon Rider",RarityStats.covert},
            {"Curse",RarityStats.restricted},
            {"Nuclear Garden",RarityStats.milSpec},
            {"Heat",RarityStats.restricted},
            {"Tornado",RarityStats.consumerGrade},
            {"Surfwood",RarityStats.consumerGrade},
            {"Aloha",RarityStats.milSpec},
            {"Malachite",RarityStats.restricted},
            {"Last Dive",RarityStats.restricted},
            {"Urban DDPAT",RarityStats.consumerGrade},
            {"Pipe Down",RarityStats.restricted},
            {"Allure",RarityStats.restricted},
            {"Strats",RarityStats.consumerGrade},
            {"Button Masher",RarityStats.restricted},
            {"Sakkaku",RarityStats.restricted},
            {"Lapis Gator",RarityStats.milSpec},
            {"Sienna Damask",RarityStats.consumerGrade},
            {"Echoing Sands",RarityStats.industrialGrade},
            {"Whitefish",RarityStats.milSpec},
            {"Rangeen",RarityStats.milSpec},
            {"Carnivore",RarityStats.milSpec},
            {"Classic Crate",RarityStats.milSpec},
            {"Oceanic",RarityStats.milSpec},
            {"Monkeyflage",RarityStats.milSpec},
            {"Ensnared",RarityStats.milSpec},
            {"Palm",RarityStats.industrialGrade},
            {"Candy Apple",RarityStats.industrialGrade},
            {"Calf Skin",RarityStats.industrialGrade},
            {"Silver",RarityStats.industrialGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsMP9 = new Dictionary<string, RarityStats>()
        {
            {"Wild Lily",RarityStats.classified},
            {"Bulldozer",RarityStats.restricted},
            {"Pandora's Box",RarityStats.milSpec},
            {"Hot Rod",RarityStats.milSpec},
            {"Dark Age",RarityStats.milSpec},
            {"Stained Glass",RarityStats.restricted},
            {"Storm",RarityStats.consumerGrade},
            {"Starlight Protector",RarityStats.covert},
            {"Music Box",RarityStats.milSpec},
            {"Hydra",RarityStats.classified},
            {"Hypnotic",RarityStats.restricted},
            {"Setting Sun",RarityStats.milSpec},
            {"Mount Fuji",RarityStats.restricted},
            {"Airlock",RarityStats.classified},
            {"Food Chain",RarityStats.classified},
            {"Rose Iron",RarityStats.restricted},
            {"Green Plaid",RarityStats.consumerGrade},
            {"Old Roots",RarityStats.industrialGrade},
            {"Dry Season",RarityStats.consumerGrade},
            {"Deadly Poison",RarityStats.milSpec},
            {"Ruby Poison Dart",RarityStats.restricted},
            {"Goo",RarityStats.restricted},
            {"Army Sheen",RarityStats.consumerGrade},
            {"Dart",RarityStats.milSpec},
            {"Capillary",RarityStats.milSpec},
            {"Orange Peel",RarityStats.industrialGrade},
            {"Bioleak",RarityStats.milSpec},
            {"Featherweight",RarityStats.milSpec},
            {"Sand Scale",RarityStats.milSpec},
            {"Black Sand",RarityStats.milSpec},
            {"Modest Threat",RarityStats.milSpec},
            {"Slide",RarityStats.consumerGrade},
            {"Sand Dashed",RarityStats.consumerGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsMP7 = new Dictionary<string, RarityStats>()
        {
            {"Teal Blossom",RarityStats.milSpec},
            {"Whiteout",RarityStats.milSpec},
            {"Full Stop",RarityStats.milSpec},
            {"Skulls",RarityStats.milSpec},
            {"Orange Peel",RarityStats.industrialGrade},
            {"Nemesis",RarityStats.classified},
            {"Gunsmoke",RarityStats.industrialGrade},
            {"Scorched",RarityStats.consumerGrade},
            {"Fade",RarityStats.restricted},
            {"Abyssal Apparition",RarityStats.classified},
            {"Asterion",RarityStats.consumerGrade},
            {"Groundwater",RarityStats.consumerGrade},
            {"Neon Ply",RarityStats.restricted},
            {"Powercore",RarityStats.restricted},
            {"Tall Grass",RarityStats.industrialGrade},
            {"Impire",RarityStats.restricted},
            {"Olive Plaid",RarityStats.consumerGrade},
            {"Special Delivery",RarityStats.restricted},
            {"Ocean Foam",RarityStats.restricted},
            {"Bloodsport",RarityStats.covert},
            {"Vault Heist",RarityStats.industrialGrade},
            {"Guerrilla",RarityStats.milSpec},
            {"Prey",RarityStats.consumerGrade},
            {"Anodized Navy",RarityStats.milSpec},
            {"Cirrus",RarityStats.milSpec},
            {"Mischief",RarityStats.milSpec},
            {"Akoben",RarityStats.milSpec},
            {"Armor Core",RarityStats.milSpec},
            {"Urban Hazard",RarityStats.milSpec},
            {"Sunbaked",RarityStats.consumerGrade},
            {"Motherboard",RarityStats.industrialGrade},
            {"Forest DDPAT",RarityStats.consumerGrade},
            {"Army Recon",RarityStats.consumerGrade}
        };
        public static Dictionary<string, RarityStats> ListSkinsMP5SD = new Dictionary<string, RarityStats>()
        {
            {"Oxide Oasis",RarityStats.classified},
            {"Phosphor",RarityStats.classified},
            {"Nitro",RarityStats.industrialGrade},
            {"Autumn Twilly",RarityStats.restricted},
            {"Bamboo Garden",RarityStats.consumerGrade},
            {"Agent",RarityStats.restricted},
            {"Gauss",RarityStats.restricted},
            {"Kitbash",RarityStats.restricted},
            {"Acid Wash",RarityStats.milSpec},
            {"Condition Zero",RarityStats.milSpec},
            {"Co-Processor",RarityStats.milSpec},
            {"Desert Strike",RarityStats.milSpec},
            {"Liquidation",RarityStats.milSpec},
            {"Necro Jr.",RarityStats.milSpec},
            {"Dirt Drop",RarityStats.consumerGrade},
            {"Lab Rats",RarityStats.restricted}

        };
        public static Dictionary<string, RarityStats> ListSkinsUMP45 = new Dictionary<string, RarityStats>()
        {
            {"Fade",RarityStats.classified},
            {"Minotaur's Labyrinth",RarityStats.milSpec},
            {"Day Lily",RarityStats.milSpec},
            {"Crime Scene",RarityStats.restricted},
            {"Caramel",RarityStats.consumerGrade},
            {"Blaze",RarityStats.milSpec},
            {"Indigo",RarityStats.consumerGrade},
            {"Fallout Warning",RarityStats.industrialGrade},
            {"Momentum",RarityStats.classified},
            {"Primal Saber",RarityStats.classified},
            {"Bone Pile",RarityStats.milSpec},
            {"Gold Bismuth",RarityStats.restricted},
            {"Wild Child",RarityStats.classified},
            {"Mechanism",RarityStats.industrialGrade},
            {"Metal Flowers",RarityStats.milSpec},
            {"Houndstooth",RarityStats.industrialGrade},
            {"Scaffold",RarityStats.restricted},
            {"Delusion",RarityStats.milSpec},
            {"Plastique",RarityStats.restricted},
            {"Full Stop",RarityStats.milSpec},
            {"Scorched",RarityStats.consumerGrade},
            {"Exposure",RarityStats.restricted},
            {"Arctic Wolf",RarityStats.restricted},
            {"Moonrise",RarityStats.restricted},
            {"Corporal",RarityStats.milSpec},
            {"Grand Prix",RarityStats.restricted},
            {"Oscillator",RarityStats.milSpec},
            {"Riot",RarityStats.milSpec},
            {"Briefing",RarityStats.milSpec},
            {"Roadblock",RarityStats.milSpec},
            {"Labyrinth",RarityStats.milSpec},
            {"Gunsmoke",RarityStats.industrialGrade},
            {"Carbon Fiber",RarityStats.industrialGrade},
            {"Urban DDPAT",RarityStats.consumerGrade},
            {"Mudder",RarityStats.consumerGrade},
            {"Facility Dark",RarityStats.consumerGrade}


        };
        public static Dictionary<string, RarityStats> ListSkinsP90 = new Dictionary<string, RarityStats>()
        {
            {"Astral Jörmungandr",RarityStats.restricted},
            {"Run and Hide",RarityStats.classified},
            {"Emerald Dragon",RarityStats.classified},
            {"Cold Blooded",RarityStats.classified},
            {"Death by Kitty",RarityStats.covert},
            {"Asiimov",RarityStats.covert},
            {"Baroque Red",RarityStats.milSpec},
            {"Sunset Lily",RarityStats.industrialGrade},
            {"Fallout Warning",RarityStats.industrialGrade},
            {"Leather",RarityStats.industrialGrade},
            {"Storm",RarityStats.consumerGrade},
            {"Tiger Pit",RarityStats.milSpec},
            {"Schematic",RarityStats.milSpec},
            {"Trigon",RarityStats.classified},
            {"ScaraB Rush",RarityStats.restricted},
            {"Blind Spot",RarityStats.restricted},
            {"Nostalgia",RarityStats.classified},
            {"Death Grip",RarityStats.restricted},
            {"Shapewood",RarityStats.classified},
            {"Glacier Mesh",RarityStats.milSpec},
            {"Shallow Grave",RarityStats.classified},
            {"Desert Warfare",RarityStats.milSpec},
            {"Verdant Growth",RarityStats.industrialGrade},
            {"Virus",RarityStats.restricted},
            {"Module",RarityStats.milSpec},
            {"Scorched",RarityStats.consumerGrade},
            {"Chopper",RarityStats.restricted},
            {"Vent Rush",RarityStats.restricted},
            {"Neoqueen",RarityStats.restricted},
            {"Traction",RarityStats.milSpec},
            {"Cocoa Rampage",RarityStats.milSpec},
            {"Elite Build",RarityStats.milSpec},
            {"Desert DDPAT",RarityStats.consumerGrade},
            {"Ancient Earth",RarityStats.consumerGrade},
            {"Facility Negative",RarityStats.milSpec},
            {"Off World",RarityStats.milSpec},
            {"Teardown",RarityStats.milSpec},
            {"Grim",RarityStats.milSpec},
            {"Freight",RarityStats.milSpec},
            {"Ash Wood",RarityStats.industrialGrade},
            {"Sand Spray",RarityStats.consumerGrade}
        };
        public static Dictionary<string, RarityStats> ListSkinsPP19Bison = new Dictionary<string, RarityStats>()
        {
            {"Rust Coat",RarityStats.milSpec},
            {"Carbon Fiber",RarityStats.industrialGrade},
            {"Modern Hunter",RarityStats.milSpec},
            {"High Roller",RarityStats.classified},
            {"Antique",RarityStats.restricted},
            {"Judgement of Anubis",RarityStats.covert},
            {"Blue Streak",RarityStats.restricted},
            {"Embargo",RarityStats.restricted},
            {"Bamboo Print",RarityStats.consumerGrade},
            {"Chemical Green",RarityStats.industrialGrade},
            {"Seabird",RarityStats.consumerGrade},
            {"Breaker Box",RarityStats.industrialGrade},
            {"Irradiated Alert",RarityStats.consumerGrade},
            {"Forest Leaves",RarityStats.consumerGrade},
            {"Water Sigil",RarityStats.milSpec},
            {"Fuel Rod",RarityStats.restricted},
            {"Cobalt Halftone",RarityStats.milSpec},
            {"Brass",RarityStats.milSpec},
            {"Photic Zone",RarityStats.milSpec},
            {"Lumen",RarityStats.milSpec},
            {"Osiris",RarityStats.restricted},
            {"Space Cat",RarityStats.restricted},
            {"Anolis",RarityStats.consumerGrade},
            {"Death Rattle",RarityStats.consumerGrade},
            {"Harvester",RarityStats.milSpec},
            {"Jungle Slipstream",RarityStats.milSpec},
            {"Runic",RarityStats.milSpec},
            {"Night Riot",RarityStats.milSpec},
            {"Candy Apple",RarityStats.industrialGrade},
            {"Night Ops",RarityStats.industrialGrade},
            {"Urban Dashed",RarityStats.consumerGrade},
            {"Sand Dashed",RarityStats.consumerGrade},
            {"Facility Sketch",RarityStats.consumerGrade}
        };
    }
}
