using Analyzer.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;

namespace Analyzer.Models.Static
{
    public static class Pistols
    {
        public static Dictionary<string, string> ListPistols = new Dictionary<string, string>() {
            { "Glock-18","ListSkinsGlock18" },
            { "USP-S","ListSkinsUSPS" },
            { "P2000","ListSkinsP2000" },
            { "P250","ListSkinsP250" },
            { "Dual Berettas","ListSkinsDualBerettas" },
            { "Five-SeveN","ListSkinsFiveSeveN" },
            { "Tec-9","ListSkinsTec9" },
            { "CZ75-Auto","ListSkinsCZ75Auto" },
            { "Revolver","ListSkinsRevolver" },
            { "Desert Eagle","ListSkinsDesertEagle" }
        };

        public static Dictionary<string, RarityStats> ListSkinsGlock18 = new Dictionary<string, RarityStats> {
            {"Fade",RarityStats.restricted},
            {"Gamma Doppler Emerald",RarityStats.covert},
            {"Synth Leaf",RarityStats.restricted},
            {"Twilight Galaxy",RarityStats.classified},
            {"Sand Dune",RarityStats.industrialGrade},
            {"Dragon Tattoo",RarityStats.restricted},
            {"Brass",RarityStats.restricted},
            {"Gamma Doppler Phase 2",RarityStats.covert},
            {"Pink DDPAT",RarityStats.restricted},
            {"Gamma Doppler Phase 1",RarityStats.covert},
            {"Gamma Doppler Phase 4",RarityStats.covert},
            {"Gamma Doppler Phase 3",RarityStats.covert},
            {"Groundwater",RarityStats.industrialGrade},
            {"Neo-Noir",RarityStats.covert},
            {"Night",RarityStats.industrialGrade},
            {"Franklin",RarityStats.restricted},
            {"Bullet Queen",RarityStats.covert},
            {"Snack Attack",RarityStats.classified},
            {"Blue Fissure",RarityStats.milSpec},
            {"Ramese's Reach",RarityStats.restricted},
            {"Water Elemental",RarityStats.classified},
            {"Reactor",RarityStats.milSpec},
            {"Vogue",RarityStats.classified},
            {"Nuclear Garden",RarityStats.restricted},
            {"Royal Legion",RarityStats.restricted},
            {"Wasteland Rebel",RarityStats.covert},
            {"Red Tire",RarityStats.industrialGrade},
            {"Steel Disruption",RarityStats.restricted},
            {"Grinder",RarityStats.restricted},
            {"Weasel",RarityStats.restricted},
            {"Umbral Rabbit",RarityStats.restricted},
            {"Moonrise",RarityStats.restricted},
            {"Bunsen Burner",RarityStats.milSpec},
            {"Ironwork",RarityStats.milSpec},
            {"Sacrifice",RarityStats.milSpec},
            {"Catacombs",RarityStats.milSpec},
            {"Wraiths",RarityStats.milSpec},
            {"Clear Polymer",RarityStats.milSpec},
            {"Candy Apple",RarityStats.milSpec},
            {"Off World",RarityStats.milSpec},
            {"Warhawk",RarityStats.milSpec},
            {"Oxide Blaze",RarityStats.milSpec},
            {"Winterized",RarityStats.milSpec},
            {"High Beam",RarityStats.industrialGrade},
            {"Death Rattle",RarityStats.industrialGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsUSPS = new Dictionary<string, RarityStats>() {
            {"Whiteout",RarityStats.classified},
            {"Target Acquired",RarityStats.classified},
            {"Kill Confirmed",RarityStats.covert},
            {"Printstream",RarityStats.covert},
            {"Orange Anolis",RarityStats.restricted},
            {"Dark Water",RarityStats.restricted},
            {"Road Rash",RarityStats.restricted},
            {"Overgrowth",RarityStats.restricted},
            {"Caiman",RarityStats.classified},
            {"Royal Blue",RarityStats.industrialGrade},
            {"Orion",RarityStats.classified},
            {"The Traitor",RarityStats.covert},
            {"Ancient Visions",RarityStats.restricted},
            {"Serum",RarityStats.classified},
            {"Business Class",RarityStats.milSpec},
            {"Monster Mashup",RarityStats.classified},
            {"Neo-Noir",RarityStats.covert},
            {"Blueprint",RarityStats.milSpec},
            {"Pathfinder",RarityStats.industrialGrade},
            {"Purple DDPAT",RarityStats.milSpec},
            {"Stainless",RarityStats.milSpec},
            {"Para Green",RarityStats.industrialGrade},
            {"Cortex",RarityStats.classified},
            {"Black Lotus",RarityStats.milSpec},
            {"Blood Tiger",RarityStats.milSpec},
            {"Guardian",RarityStats.restricted},
            {"Lead Conduit",RarityStats.milSpec},
            {"Cyrex",RarityStats.restricted},
            {"Torque",RarityStats.milSpec},
            {"Check Engine",RarityStats.milSpec},
            {"Ticket to Hell",RarityStats.restricted},
            {"Flashback",RarityStats.restricted},
            {"Forest Leaves",RarityStats.industrialGrade},
            {"Desert Tactical",RarityStats.industrialGrade},
            {"Night Ops",RarityStats.milSpec}
        };
        public static Dictionary<string, RarityStats> ListSkinsP2000 = new Dictionary<string, RarityStats>() {
            {"Ocean Foam",RarityStats.classified},
            {"Chainmail",RarityStats.milSpec},
            {"Silver",RarityStats.milSpec},
            {"Dispatch",RarityStats.milSpec},
            {"Fire Elemental",RarityStats.covert},
            {"Pathfinder",RarityStats.industrialGrade},
            {"Corticera",RarityStats.classified},
            {"Coach Class",RarityStats.industrialGrade},
            {"Grassland",RarityStats.industrialGrade},
            {"Grassland Leaves",RarityStats.industrialGrade},
            {"Wicked Sick",RarityStats.classified},
            {"Woodsman",RarityStats.restricted},
            {"Amber Fade",RarityStats.restricted},
            {"Space Race",RarityStats.restricted},
            {"Imperial Dragon",RarityStats.classified},
            {"Obsidian",RarityStats.restricted},
            {"Scorpion",RarityStats.restricted},
            {"Panther Camo",RarityStats.industrialGrade},
            {"Handgun",RarityStats.restricted},
            {"Pulse",RarityStats.milSpec},
            {"Red FragCam",RarityStats.milSpec},
            {"Acid Etched",RarityStats.restricted},
            {"Turf",RarityStats.milSpec},
            {"Ivory",RarityStats.milSpec},
            {"Imperial",RarityStats.milSpec},
            {"Oceanic",RarityStats.milSpec},
            {"Gnarled",RarityStats.milSpec},
            {"Urban Hazard",RarityStats.milSpec},
            {"Lifted Spirits",RarityStats.milSpec},
            {"Granite Marbleized",RarityStats.industrialGrade}
        };
        public static Dictionary<string, RarityStats> ListSkinsP250 = new Dictionary<string, RarityStats>() {
            {"Whiteout",RarityStats.milSpec},
            {"Apep's Curse",RarityStats.classified},
            {"Nuclear Threat",RarityStats.restricted},
            {"Digital Architect",RarityStats.restricted},
            {"Undertow",RarityStats.classified},
            {"Splash",RarityStats.restricted},
            {"Facets",RarityStats.industrialGrade},
            {"Bengal Tiger",RarityStats.milSpec},
            {"Black & Tan",RarityStats.milSpec},
            {"Crimson Kimono",RarityStats.industrialGrade},
            {"Mehndi",RarityStats.classified},
            {"Modern Hunter",RarityStats.milSpec},
            {"Asiimov",RarityStats.classified},
            {"Cartel",RarityStats.classified},
            {"Dark Filigree",RarityStats.industrialGrade},
            {"Red Rock",RarityStats.restricted},
            {"See Ya Later",RarityStats.covert},
            {"Visions",RarityStats.classified},
            {"Muertos",RarityStats.classified},
            {"Vino Primo",RarityStats.restricted},
            {"Hive",RarityStats.milSpec},
            {"Mint Kimono",RarityStats.consumerGrade},
            {"Gunsmoke",RarityStats.industrialGrade},
            {"Wingshot",RarityStats.restricted},
            {"Bone Mask",RarityStats.consumerGrade},
            {"Contamination",RarityStats.industrialGrade},
            {"Steel Disruption",RarityStats.milSpec},
            {"Forest Night",RarityStats.consumerGrade},
            {"Inferno",RarityStats.restricted},
            {"Supernova",RarityStats.restricted},
            {"Nevermore",RarityStats.restricted},
            {"Franklin",RarityStats.classified},
            {"Cyber Shell",RarityStats.restricted},
            {"Contaminant",RarityStats.milSpec},
            {"Drought",RarityStats.consumerGrade},
            {"Valence",RarityStats.milSpec},
            {"Exchanger",RarityStats.milSpec},
            {"Verdigris",RarityStats.milSpec},
            {"X-Ray",RarityStats.restricted},
            {"Iron Clad",RarityStats.milSpec},
            {"Ripple",RarityStats.milSpec},
            {"Sand Dune",RarityStats.consumerGrade},
            {"Re.built",RarityStats.milSpec},
            {"Cassette",RarityStats.milSpec},
            {"Metallic DDPAT",RarityStats.industrialGrade},
            {"Boreal Forest",RarityStats.consumerGrade},
            {"Facility Draft",RarityStats.consumerGrade},
        };
        public static Dictionary<string, RarityStats> ListSkinsDualBerettas = new Dictionary<string, RarityStats>()
        {
            {"Duelist",RarityStats.restricted},
            {"Cobra Strike",RarityStats.classified},
            {"Emerald",RarityStats.milSpec},
            {"Pyre",RarityStats.industrialGrade},
            {"Marina",RarityStats.restricted},
            {"Demolition",RarityStats.restricted},
            {"Black Limba",RarityStats.milSpec},
            {"Hemoglobin",RarityStats.restricted},
            {"Melondrama",RarityStats.classified},
            {"Dezastre",RarityStats.restricted},
            {"Switch Board",RarityStats.industrialGrade},
            {"Moon in Libra",RarityStats.consumerGrade},
            {"Anodized Navy",RarityStats.milSpec},
            {"Twin Turbo",RarityStats.classified},
            {"Briar",RarityStats.consumerGrade},
            {"Drift Wood",RarityStats.industrialGrade},
            {"Retribution",RarityStats.milSpec},
            {"Urban Shock",RarityStats.restricted},
            {"Balance",RarityStats.milSpec},
            {"Panther",RarityStats.milSpec},
            {"Royal Consorts",RarityStats.restricted},
            {"Flora Carnivora",RarityStats.restricted},
            {"Dualing Dragons",RarityStats.milSpec},
            {"Tread",RarityStats.milSpec},
            {"Cartel",RarityStats.milSpec},
            {"Oil Change",RarityStats.consumerGrade},
            {"Heist",RarityStats.consumerGrade},
            {"Shred",RarityStats.milSpec},
            {"Elite 1.6",RarityStats.milSpec},
            {"Ventilators",RarityStats.milSpec},
            {"Cobalt Quartz",RarityStats.restricted},
            {"Stained",RarityStats.industrialGrade},
            {"Colony",RarityStats.consumerGrade},
            {"Contractor",RarityStats.consumerGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsFiveSeveN = new Dictionary<string, RarityStats>()
        {
            {"Neon Kimono",RarityStats.restricted},
            {"Fall Hazard",RarityStats.classified},
            {"Crimson Blossom",RarityStats.milSpec},
            {"Berries And Cherries",RarityStats.restricted},
            {"Hyper Beast",RarityStats.covert},
            {"Candy Apple",RarityStats.industrialGrade},
            {"Fairy Tale",RarityStats.classified},
            {"Nitro",RarityStats.milSpec},
            {"Case Hardened",RarityStats.restricted},
            {"Hot Shot",RarityStats.industrialGrade},
            {"Angry Mob",RarityStats.covert},
            {"Contractor",RarityStats.consumerGrade},
            {"Monkey Business",RarityStats.classified},
            {"Anodized Gunmetal",RarityStats.consumerGrade},
            {"Fowl Play",RarityStats.classified},
            {"Copper Galaxy",RarityStats.restricted},
            {"Jungle",RarityStats.consumerGrade},
            {"Withered Vine",RarityStats.industrialGrade},
            {"Triumvirate",RarityStats.restricted},
            {"Boost Protocol",RarityStats.restricted},
            {"Retrobution",RarityStats.restricted},
            {"Nightshade",RarityStats.milSpec},
            {"Kami",RarityStats.milSpec},
            {"Buddy",RarityStats.restricted},
            {"Urban Hazard",RarityStats.milSpec},
            {"Violent Daimyo",RarityStats.milSpec},
            {"Silver Quartz",RarityStats.milSpec},
            {"Capillary",RarityStats.milSpec},
            {"Scumbria",RarityStats.milSpec},
            {"Orange Peel",RarityStats.industrialGrade},
            {"Scrawl",RarityStats.milSpec},
            {"Flame Test",RarityStats.milSpec},
            {"Forest Night",RarityStats.consumerGrade},
            {"Coolant",RarityStats.consumerGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsTec9 = new Dictionary<string, RarityStats>()
        {
            {"Terrace",RarityStats.milSpec},
            {"Nuclear Threat",RarityStats.restricted},
            {"Brass",RarityStats.milSpec},
            {"Decimator",RarityStats.classified},
            {"Rust Leaf",RarityStats.industrialGrade},
            {"Hades",RarityStats.industrialGrade},
            {"Blast From the Past",RarityStats.milSpec},
            {"Fuel Injector",RarityStats.classified},
            {"Isaac",RarityStats.milSpec},
            {"Toxic",RarityStats.milSpec},
            {"Orange Murano",RarityStats.industrialGrade},
            {"Tornado",RarityStats.consumerGrade},
            {"Cut Out",RarityStats.milSpec},
            {"Bamboo Forest",RarityStats.consumerGrade},
            {"Blue Titanium",RarityStats.milSpec},
            {"Titanium Bit",RarityStats.restricted},
            {"Remote Control",RarityStats.classified},
            {"Avalanche",RarityStats.restricted},
            {"Ossified",RarityStats.milSpec},
            {"Mummy's Rot",RarityStats.milSpec},
            {"Safety Net",RarityStats.milSpec},
            {"Bamboozle",RarityStats.restricted},
            {"Re-Entry",RarityStats.restricted},
            {"Brother",RarityStats.restricted},
            {"Sandstorm",RarityStats.milSpec},
            {"Jambiya",RarityStats.milSpec},
            {"Fubar",RarityStats.milSpec},
            {"Snek-9",RarityStats.milSpec},
            {"Phoenix Chalk",RarityStats.consumerGrade},
            {"Cracked Opal",RarityStats.milSpec},
            {"Ice Cap",RarityStats.milSpec},
            {"Flash Out",RarityStats.milSpec},
            {"Rebel",RarityStats.milSpec},
            {"Red Quartz",RarityStats.restricted},
            {"Groundwater",RarityStats.consumerGrade},
            {"VariCamo",RarityStats.industrialGrade},
            {"Urban DDPAT",RarityStats.consumerGrade},
            {"Army Mesh",RarityStats.consumerGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsCZ75Auto = new Dictionary<string, RarityStats>() {
            {"Chalice", RarityStats.restricted},
            {"Emerald Quartz",RarityStats.milSpec},
            { "The Fuschia Is Now",RarityStats.classified},
            { "Emerald",RarityStats.milSpec},
            { "Crimson Web",RarityStats.milSpec},
            { "Yellow Jacket",RarityStats.classified},
            { "Nitro",RarityStats.milSpec},
            { "Xiangliu",RarityStats.classified},
            { "Victoria",RarityStats.covert},
            { "Hexane",RarityStats.milSpec},
            { "Syndicate",RarityStats.restricted},
            { "Poison Dart",RarityStats.milSpec},
            { "Tread Plate",RarityStats.restricted},
            { "Indigo",RarityStats.consumerGrade},
            { "Silver",RarityStats.industrialGrade},
            { "Green Plaid",RarityStats.consumerGrade},
            { "Eco",RarityStats.restricted},
            { "Midnight Palm",RarityStats.industrialGrade},
            { "Army Sheen",RarityStats.consumerGrade},
            { "Twist",RarityStats.milSpec},
            { "Pole Position",RarityStats.restricted},
            { "Tigris",RarityStats.restricted},
            { "Jungle Dashed",RarityStats.consumerGrade},
            { "Framework",RarityStats.consumerGrade},
            { "Red Astor",RarityStats.restricted},
            { "Tacticat",RarityStats.restricted},
            { "Vendetta",RarityStats.milSpec},
            { "Tuxedo",RarityStats.milSpec},
            { "Circaetus",RarityStats.milSpec},
            { "Imprint",RarityStats.milSpec},
            { "Distressed",RarityStats.milSpec},
            { "Polymer",RarityStats.milSpec}
        };
        public static Dictionary<string, RarityStats> ListSkinsRevolver = new Dictionary<string, RarityStats>() {
            {"Fade",RarityStats.covert},
            {"Llama Cannon",RarityStats.classified},
            {"Canal Spray",RarityStats.consumerGrade},
            {"Night",RarityStats.consumerGrade},
            {"Crimson Web",RarityStats.milSpec},
            {"Phoenix Marker",RarityStats.industrialGrade},
            {"Reboot",RarityStats.restricted},
            {"Memento",RarityStats.milSpec},
            {"Crazy 8",RarityStats.restricted},
            {"Blaze",RarityStats.milSpec},
            {"Banana Cannon",RarityStats.restricted},
            {"Skull Crusher",RarityStats.classified},
            {"Amber Fade",RarityStats.classified},
            {"Desert Brush",RarityStats.consumerGrade},
            {"Junk Yard",RarityStats.milSpec},
            {"Survivalist",RarityStats.milSpec},
            {"Bone Forged",RarityStats.milSpec},
            {"Grip",RarityStats.milSpec},
            {"Nitro",RarityStats.industrialGrade},
            {"Inlay",RarityStats.consumerGrade},
            {"Bone Mask",RarityStats.consumerGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsDesertEagle = new Dictionary<string, RarityStats>() {
            {"Blaze",RarityStats.restricted},
            {"Hand Cannon",RarityStats.restricted},
            {"Fennec Fox",RarityStats.classified},
            {"Emerald Jörmungandr",RarityStats.restricted},
            {"Sunset Storm 弐",RarityStats.restricted},
            {"Sunset Storm 壱",RarityStats.restricted},
            {"Pilot",RarityStats.restricted},
            {"Ocean Drive",RarityStats.covert},
            {"Golden Koi",RarityStats.covert},
            {"Hypnotic",RarityStats.classified},
            {"Crimson Web",RarityStats.restricted},
            {"Cobalt Disruption",RarityStats.classified},
            {"Printstream",RarityStats.covert},
            {"Code Red",RarityStats.covert},
            {"Night",RarityStats.industrialGrade},
            {"Kumicho Dragon",RarityStats.classified},
            {"Midnight Storm",RarityStats.industrialGrade},
            {"Urban DDPAT",RarityStats.industrialGrade},
            {"Night Heist",RarityStats.milSpec},
            {"Heirloom",RarityStats.restricted},
            {"Directive",RarityStats.restricted},
            {"Mecha Industries",RarityStats.classified},
            {"Conspiracy",RarityStats.classified},
            {"The Bronze",RarityStats.industrialGrade},
            {"Naga",RarityStats.restricted},
            {"Light Rail",RarityStats.restricted},
            {"Trigger Discipline",RarityStats.restricted},
            {"Sputnik",RarityStats.milSpec},
            {"Blue Ply",RarityStats.milSpec},
            {"Meteorite",RarityStats.milSpec},
            {"Corinthian",RarityStats.milSpec},
            {"Oxide Blaze",RarityStats.milSpec},
            {"Urban Rubble",RarityStats.milSpec},
            {"Bronze Deco",RarityStats.milSpec},
            {"Mudder",RarityStats.industrialGrade}
        };
    }

}
