using Analyzer.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Analyzer.Models.StaticClasses
{
    public static class Rifles
    {
        public static Dictionary<string, string> ListRifles = new Dictionary<string, string>() {
            { "FAMAS","ListSkinsFAMAS"},
            { "Galil AR","ListSkinsGalilAR" },
            { "M4A1","ListSkinsM4A1" },
            { "M4A1-S","ListSkinsM4A1" },
            { "AK-47" ,"ListSkinsAK47"},
            { "AUG","ListSkinsAUG"},
            { "SG 553","ListSkinsSG553" },
            { "SSG 08","ListSkinsSSG08"},
            { "AWP","ListSkinsAWP" },
            { "SCAR-20","ListSkinsSCAR20"},
            { "G3SG1","ListSkinsG3SG1"}
        };

        public static Dictionary<string, RarityStats> ListSkinsFAMAS = new Dictionary<string, RarityStats>() {
            {"Spitfire",RarityStats.restricted},
            {"Sundown",RarityStats.milSpec},
            {"Waters of Nephthys",RarityStats.classified},
            {"Prime Conspiracy",RarityStats.restricted},
            {"Afterimage",RarityStats.classified},
            {"Meltdown",RarityStats.classified},
            {"Commemoration",RarityStats.covert},
            {"Dark Water",RarityStats.milSpec},
            {"Roll Cage",RarityStats.covert},
            {"Eye of Athena",RarityStats.classified},
            {"Djinn",RarityStats.classified},
            {"Styx",RarityStats.restricted},
            {"Night Borre",RarityStats.consumerGrade},
            {"Contrast Spray",RarityStats.consumerGrade},
            {"Mecha Industries",RarityStats.classified},
            {"Pulse",RarityStats.restricted},
            {"Rapid Eye Movement",RarityStats.classified},
            {"Hexane",RarityStats.milSpec},
            {"Valence",RarityStats.restricted},
            {"ZX Spectron",RarityStats.restricted},
            {"Doomkitty",RarityStats.milSpec},
            {"Sergeant",RarityStats.restricted},
            {"Macabre",RarityStats.milSpec},
            {"CaliCamo",RarityStats.industrialGrade},
            {"Neural Net",RarityStats.restricted},
            {"Faulty Wiring",RarityStats.consumerGrade},
            {"Cyanospatter",RarityStats.industrialGrade},
            {"Teardown",RarityStats.milSpec},
            {"Survivor Z",RarityStats.milSpec},
            {"Crypsis",RarityStats.milSpec},
            {"Decommissioned",RarityStats.milSpec},
            {"Meow 36",RarityStats.milSpec},
            {"Colony",RarityStats.consumerGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsGalilAR = new Dictionary<string, RarityStats>()
        {
            {"Aqua Terrace",RarityStats.milSpec},
            {"Chatterbox",RarityStats.covert},
            {"Phoenix Blacklight",RarityStats.restricted},
            {"Cerberus",RarityStats.restricted},
            {"Sugar Rush",RarityStats.classified},
            {"CAUTION!",RarityStats.restricted},
            {"Eco",RarityStats.classified},
            {"Amber Fade",RarityStats.milSpec},
            {"Winter Forest",RarityStats.industrialGrade},
            {"Urban Rubble",RarityStats.industrialGrade},
            {"Orange DDPAT",RarityStats.restricted},
            {"Dusk Ruins",RarityStats.milSpec},
            {"Tornado",RarityStats.consumerGrade},
            {"Chromatic Aberration",RarityStats.classified},
            {"Shattered",RarityStats.milSpec},
            {"Rocket Pop",RarityStats.milSpec},
            {"Stone Cold",RarityStats.restricted},
            {"Hunting Blind",RarityStats.consumerGrade},
            {"Blue Titanium",RarityStats.milSpec},
            {"Crimson Tsunami",RarityStats.restricted},
            {"Kami",RarityStats.milSpec},
            {"Sandstorm",RarityStats.milSpec},
            {"Firefight",RarityStats.restricted},
            {"Vandal",RarityStats.milSpec},
            {"Signal",RarityStats.restricted},
            {"Tuxedo",RarityStats.milSpec},
            {"Connexion",RarityStats.restricted},
            {"Akoben",RarityStats.milSpec},
            {"Black Sand",RarityStats.milSpec},
            {"Cold Fusion",RarityStats.industrialGrade},
            {"Destroyer",RarityStats.milSpec},
            {"Sage Spray",RarityStats.consumerGrade},
            {"VariCamo",RarityStats.industrialGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsM4A1 = new Dictionary<string, RarityStats>()
        {
            {"Howl",RarityStats.contraband},
            {"Poseidon",RarityStats.classified},
            {"Eye of Horus",RarityStats.covert},
            {"Radiation Hazard",RarityStats.milSpec},
            {"The Coalition",RarityStats.covert},
            {"Daybreak",RarityStats.restricted},
            {"Tornado",RarityStats.industrialGrade},
            {"Asiimov",RarityStats.covert},
            {"The Emperor",RarityStats.covert},
            {"Temukau",RarityStats.covert},
            {"Royal Paladin",RarityStats.covert},
            {"Red DDPAT",RarityStats.restricted},
            {"Jungle Tiger",RarityStats.industrialGrade},
            {"Modern Hunter",RarityStats.restricted},
            {"Hellfire",RarityStats.classified},
            {"Bullet Rain",RarityStats.covert},
            {"Cyber Security",RarityStats.classified},
            {"Desert Storm",RarityStats.industrialGrade},
            {"Zirka",RarityStats.restricted},
            {"Neo-Noir",RarityStats.covert},
            {"In Living Color",RarityStats.covert},
            {"Global Offensive",RarityStats.milSpec},
            {"Buzz Kill",RarityStats.covert},
            {"Dark Blossom",RarityStats.industrialGrade},
            {"龍王 (Dragon King)",RarityStats.classified},
            {"Faded Zebra",RarityStats.milSpec},
            {"Desolate Space",RarityStats.classified},
            {"X-Ray",RarityStats.covert},
            {"Spider Lily",RarityStats.restricted},
            {"The Battlestar",RarityStats.covert},
            {"Tooth Fairy",RarityStats.classified},
            {"Desert-Strike",RarityStats.covert},
            {"Evil Daimyo",RarityStats.restricted},
            {"Griffin",RarityStats.restricted},
            {"Urban DDPAT",RarityStats.industrialGrade},
            {"Magnesium",RarityStats.milSpec},
            {"Converter",RarityStats.milSpec},
            {"Poly Mag",RarityStats.milSpec},
            {"Mainframe",RarityStats.industrialGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsM4A1S = new Dictionary<string, RarityStats>()
        {
            {"Knight",RarityStats.classified},
            {"Welcome to the Jungle",RarityStats.covert},
            {"Imminent Danger",RarityStats.covert},
            {"Hot Rod",RarityStats.classified},
            {"Blue Phosphor",RarityStats.classified},
            {"Icarus Fell",RarityStats.restricted},
            {"Master Piece",RarityStats.classified},
            {"Printstream",RarityStats.covert},
            {"Golden Coil",RarityStats.covert},
            {"Hyper Beast",RarityStats.covert},
            {"Chantico's Fire",RarityStats.covert},
            {"Player Two",RarityStats.covert},
            {"Dark Water",RarityStats.restricted},
            {"Mecha Industries",RarityStats.covert},
            {"Atomic Alloy",RarityStats.classified},
            {"Moss Quartz",RarityStats.industrialGrade},
            {"Control Panel",RarityStats.classified},
            {"Nightmare",RarityStats.classified},
            {"Decimator",RarityStats.classified},
            {"Cyrex",RarityStats.covert},
            {"Guardian",RarityStats.classified},
            {"Bright Water",RarityStats.restricted},
            {"Basilisk",RarityStats.restricted},
            {"Leaded Glass",RarityStats.classified},
            {"Briefing",RarityStats.milSpec},
            {"Blood Tiger",RarityStats.milSpec},
            {"Nitro",RarityStats.restricted},
            {"Emphorosaur-S",RarityStats.restricted},
            {"Fizzy POP",RarityStats.milSpec},
            {"Flashback",RarityStats.restricted},
            {"Night Terror",RarityStats.restricted},
            {"Boreal Forest",RarityStats.industrialGrade},
            {"VariCamo",RarityStats.milSpec},
            {"Mud-Spec",RarityStats.industrialGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsAK47 = new Dictionary<string, RarityStats>()
        {
            {"Wild Lotus",RarityStats.covert},
            {"Gold Arabesque",RarityStats.covert},
            {"Fire Serpent",RarityStats.covert},
            {"Hydroponic",RarityStats.classified},
            {"X-Ray",RarityStats.covert},
            {"Vulcan",RarityStats.covert},
            {"Fuel Injector",RarityStats.covert},
            {"Case Hardened",RarityStats.classified},
            {"Jet Set",RarityStats.classified},
            {"Panthera onca",RarityStats.classified},
            {"Asiimov",RarityStats.covert},
            {"Jaguar",RarityStats.covert},
            {"Black Laminate",RarityStats.milSpec},
            {"First Class",RarityStats.restricted},
            {"Bloodsport",RarityStats.covert},
            {"Neon Rider",RarityStats.covert},
            {"The Empress",RarityStats.covert},
            {"Jungle Spray",RarityStats.industrialGrade},
            {"Aquamarine Revenge",RarityStats.covert},
            {"Redline",RarityStats.classified},
            {"Leet Museo",RarityStats.covert},
            {"Neon Revolution",RarityStats.covert},
            {"Frontside Misty",RarityStats.classified},
            {"Head Shot",RarityStats.covert},
            {"Nightwish",RarityStats.covert},
            {"Red Laminate",RarityStats.classified},
            {"Wasteland Rebel",RarityStats.covert},
            {"Predator",RarityStats.industrialGrade},
            {"Point Disarray",RarityStats.classified},
            {"Cartel",RarityStats.classified},
            {"Green Laminate",RarityStats.milSpec},
            {"Orbit Mk01",RarityStats.restricted},
            {"Ice Coaled",RarityStats.classified},
            {"Legion of Anubis",RarityStats.covert},
            {"Baroque Purple",RarityStats.industrialGrade},
            {"Blue Laminate",RarityStats.restricted},
            {"Rat Rod",RarityStats.restricted},
            {"Phantom Disruptor",RarityStats.classified},
            {"Slate",RarityStats.restricted},
            {"Emerald Pinstripe",RarityStats.restricted},
            {"Safety Net",RarityStats.restricted},
            {"Elite Build",RarityStats.milSpec},
            {"Steel Delta",RarityStats.milSpec},
            {"Safari Mesh",RarityStats.industrialGrade},
            {"Uncharted",RarityStats.milSpec}

        };
        public static Dictionary<string, RarityStats> ListSkinsAUG = new Dictionary<string, RarityStats>()
        {
            {"Akihabara Accept",RarityStats.covert},
            {"Hot Rod",RarityStats.milSpec},
            {"Midnight Lily",RarityStats.restricted},
            {"Flame Jörmungandr",RarityStats.restricted},
            {"Copperhead",RarityStats.milSpec},
            {"Sand Storm",RarityStats.restricted},
            {"Anodized Navy",RarityStats.milSpec},
            {"Wings",RarityStats.milSpec},
            {"Carved Jade",RarityStats.milSpec},
            {"Momentum",RarityStats.classified},
            {"Death by Puppy",RarityStats.classified},
            {"Torque",RarityStats.restricted},
            {"Fleet Flock",RarityStats.classified},
            {"Bengal Tiger",RarityStats.classified},
            {"Syd Mead",RarityStats.classified},
            {"Stymphalian",RarityStats.classified},
            {"Daedalus",RarityStats.consumerGrade},
            {"Arctic Wolf",RarityStats.restricted},
            {"Navy Murano",RarityStats.consumerGrade},
            {"Random Access",RarityStats.restricted},
            {"Chameleon",RarityStats.covert},
            {"Spalted Wood",RarityStats.industrialGrade},
            {"Colony",RarityStats.consumerGrade},
            {"Radiation Hazard",RarityStats.industrialGrade},
            {"Aristocrat",RarityStats.restricted},
            {"Amber Fade",RarityStats.milSpec},
            {"Plague",RarityStats.milSpec},
            {"Surveillance",RarityStats.consumerGrade},
            {"Ricochet",RarityStats.milSpec},
            {"Storm",RarityStats.consumerGrade},
            {"Amber Slipstream",RarityStats.milSpec},
            {"Triqua",RarityStats.milSpec},
            {"Tom Cat",RarityStats.milSpec},
            {"Condemned",RarityStats.industrialGrade},
            {"Snake Pit",RarityStats.consumerGrade},
            {"Contractor",RarityStats.consumerGrade},
            {"Sweeper",RarityStats.consumerGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsSG553 = new Dictionary<string, RarityStats>()
        {
            {"Hazard Pay",RarityStats.classified},
            {"Bulldozer",RarityStats.restricted},
            {"Integrale",RarityStats.classified},
            {"Hypnotic",RarityStats.restricted},
            {"Ultraviolet",RarityStats.milSpec},
            {"Colony IV",RarityStats.classified},
            {"Traveler",RarityStats.industrialGrade},
            {"Desert Blossom",RarityStats.milSpec},
            {"Gator Mesh",RarityStats.industrialGrade},
            {"Cyrex",RarityStats.classified},
            {"Tornado",RarityStats.consumerGrade},
            {"Wave Spray",RarityStats.milSpec},
            {"Barricade",RarityStats.consumerGrade},
            {"Candy Apple",RarityStats.industrialGrade},
            {"Pulse",RarityStats.restricted},
            {"Fallout Warning",RarityStats.industrialGrade},
            {"Tiger Moth",RarityStats.restricted},
            {"Darkwing",RarityStats.restricted},
            {"Dragon Tech",RarityStats.restricted},
            {"Triarch",RarityStats.restricted},
            {"Phantom",RarityStats.restricted},
            {"Damascus Steel",RarityStats.milSpec},
            {"Lush Ruins",RarityStats.consumerGrade},
            {"Bleached",RarityStats.consumerGrade},
            {"Anodized Navy",RarityStats.milSpec},
            {"Heavy Metal",RarityStats.milSpec},
            {"Atlas",RarityStats.milSpec},
            {"Aerial",RarityStats.milSpec},
            {"Danger Close",RarityStats.milSpec},
            {"Aloha",RarityStats.milSpec},
            {"Ol' Rusty",RarityStats.milSpec},
            {"Cyberforce",RarityStats.milSpec},
            {"Waves Perforated",RarityStats.consumerGrade},
            {"Army Sheen",RarityStats.consumerGrade}
        };
        public static Dictionary<string, RarityStats> ListSkinsSSG08 = new Dictionary<string, RarityStats>()
        {
            {"Death Strike",RarityStats.classified},
            {"Sea Calico",RarityStats.restricted},
            {"Blood in the Water",RarityStats.covert},
            {"Bloodshot",RarityStats.classified},
            {"Sand Dune",RarityStats.consumerGrade},
            {"Mayan Dreams",RarityStats.industrialGrade},
            {"Orange Filigree",RarityStats.milSpec},
            {"Threat Detected",RarityStats.milSpec},
            {"Dragonfire",RarityStats.covert},
            {"Big Iron",RarityStats.classified},
            {"Detour",RarityStats.milSpec},
            {"Red Stone",RarityStats.consumerGrade},
            {"Turbo Peek",RarityStats.classified},
            {"Tropical Storm",RarityStats.industrialGrade},
            {"Lichen Dashed",RarityStats.consumerGrade},
            {"Death's Head",RarityStats.restricted},
            {"Jungle Dashed",RarityStats.consumerGrade},
            {"Parallax",RarityStats.restricted},
            {"Carbon Fiber",RarityStats.industrialGrade},
            {"Ghost Crusader",RarityStats.restricted},
            {"Abyss",RarityStats.milSpec},
            {"Fever Dream",RarityStats.restricted},
            {"Dark Water",RarityStats.milSpec},
            {"Slashed",RarityStats.milSpec},
            {"Spring Twilly",RarityStats.milSpec},
            {"Acid Fade",RarityStats.milSpec},
            {"Necropos",RarityStats.milSpec},
            {"Hand Brake",RarityStats.milSpec},
            {"Prey",RarityStats.consumerGrade},
            {"Azure Glyph",RarityStats.industrialGrade},
            {"Mainframe 001",RarityStats.milSpec},
            {"Blue Spruce",RarityStats.consumerGrade}
        };
        public static Dictionary<string, RarityStats> ListSkinsAWP = new Dictionary<string, RarityStats>()
        {
            {"Gungnir",RarityStats.covert},
            {"Dragon Lore",RarityStats.covert},
            {"The Prince",RarityStats.covert},
            {"Medusa",RarityStats.covert},
            {"Desert Hydra",RarityStats.covert},
            {"Fade",RarityStats.covert},
            {"Lightning Strike",RarityStats.covert},
            {"Oni Taiji",RarityStats.covert},
            {"Containment Breach",RarityStats.covert},
            {"BOOM",RarityStats.classified},
            {"Silk Tiger",RarityStats.classified},
            {"Graphite",RarityStats.classified},
            {"Wildfire",RarityStats.covert},
            {"Asiimov",RarityStats.covert},
            {"Pink DDPAT",RarityStats.restricted},
            {"Snake Camo",RarityStats.milSpec},
            {"Hyper Beast",RarityStats.covert},
            {"Redline",RarityStats.classified},
            {"Electric Hive",RarityStats.classified},
            {"Sun in Leo",RarityStats.industrialGrade},
            {"Corticera",RarityStats.classified},
            {"Man-o'-war",RarityStats.covert},
            {"Neo-Noir",RarityStats.covert},
            {"Elite Build",RarityStats.classified},
            {"Chromatic Aberration",RarityStats.covert},
            {"Atheris",RarityStats.restricted},
            {"Fever Dream",RarityStats.classified},
            {"Duality",RarityStats.classified},
            {"POP AWP",RarityStats.restricted},
            {"Exoskeleton",RarityStats.restricted},
            {"Mortis",RarityStats.classified},
            {"Black Nile",RarityStats.milSpec},
            {"PAW",RarityStats.restricted},
            {"Phobos",RarityStats.restricted},
            {"Worm God",RarityStats.restricted},
            {"Capillary",RarityStats.milSpec},
            {"Acheron",RarityStats.milSpec},
            {"Safari Mesh",RarityStats.industrialGrade},
            {"Pit Viper",RarityStats.restricted}

        };
        public static Dictionary<string, RarityStats> ListSkinsSCAR20 = new Dictionary<string, RarityStats>()
        {
            {"Brass",RarityStats.milSpec},
            {"Cyrex",RarityStats.classified},
            {"Splash Jam",RarityStats.classified},
            {"Emerald",RarityStats.restricted},
            {"Magna Carta",RarityStats.milSpec},
            {"Palm",RarityStats.industrialGrade},
            {"Crimson Web",RarityStats.milSpec},
            {"Cardiac",RarityStats.classified},
            {"Storm",RarityStats.consumerGrade},
            {"Bloodsport",RarityStats.classified},
            {"Stone Mosaico",RarityStats.consumerGrade},
            {"Army Sheen",RarityStats.consumerGrade},
            {"Powercore",RarityStats.restricted},
            {"Enforcer",RarityStats.restricted},
            {"Torn",RarityStats.milSpec},
            {"Green Marine",RarityStats.milSpec},
            {"Grotto",RarityStats.milSpec},
            {"Blueprint",RarityStats.milSpec},
            {"Outbreak",RarityStats.milSpec},
            {"Assault",RarityStats.milSpec},
            {"Fragments",RarityStats.milSpec},
            {"Jungle Slipstream",RarityStats.milSpec},
            {"Poultrygeist",RarityStats.milSpec},
            {"Carbon Fiber",RarityStats.industrialGrade},
            {"Sand Mesh",RarityStats.consumerGrade},
            {"Contractor",RarityStats.consumerGrade}

        };
        public static Dictionary<string, RarityStats> ListSkinsG3SG1 = new Dictionary<string, RarityStats>()
        {
            {"Chronos",RarityStats.restricted},
            {"Violet Murano",RarityStats.milSpec},
            {"New Roots",RarityStats.milSpec},
            {"Flux",RarityStats.classified},
            {"Arctic Camo",RarityStats.industrialGrade},
            {"Demeter",RarityStats.milSpec},
            {"The Executioner",RarityStats.classified},
            {"Orange Kimono",RarityStats.consumerGrade},
            {"Ancient Ritual",RarityStats.industrialGrade},
            {"High Seas",RarityStats.restricted},
            {"Safari Mesh",RarityStats.consumerGrade},
            {"Contractor",RarityStats.consumerGrade},
            {"Azure Zebra",RarityStats.milSpec},
            {"Scavenger",RarityStats.restricted},
            {"Black Sand",RarityStats.milSpec},
            {"Keeping Tabs",RarityStats.milSpec},
            {"Stinger",RarityStats.restricted},
            {"Dream Glade",RarityStats.restricted},
            {"Digital Mesh",RarityStats.milSpec},
            {"Murky",RarityStats.milSpec},
            {"Hunter",RarityStats.milSpec},
            {"Ventilator",RarityStats.milSpec},
            {"Orange Crash",RarityStats.milSpec},
            {"Green Apple",RarityStats.industrialGrade},
            {"VariCamo",RarityStats.industrialGrade},
            {"Polar Camo",RarityStats.consumerGrade},
            {"Jungle Dashed",RarityStats.consumerGrade},
            {"Desert Storm",RarityStats.consumerGrade}
        };
    }
}
